    <script src="{{ asset('adminpanel/assets/js/jquery.min.js') }}"></script>
    <script src="{{ asset('adminpanel/assets/js/popper.min.js') }}"></script>
    <script src="{{ asset('adminpanel/assets/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('adminpanel/assets/js/modernizr.min.js') }}"></script>
    <script src="{{ asset('adminpanel/assets/js/detect.js') }}"></script>
    <script src="{{ asset('adminpanel/assets/js/fastclick.js') }}"></script>
    <script src="{{ asset('adminpanel/assets/js/jquery.slimscroll.js') }}"></script>
    <script src="{{ asset('adminpanel/assets/js/jquery.blockUI.js') }}"></script>
    <script src="{{ asset('adminpanel/assets/js/waves.js') }}"></script>
    <script src="{{ asset('adminpanel/assets/js/jquery.nicescroll.js') }}"></script>
    <script src="{{ asset('adminpanel/assets/js/jquery.scrollTo.min.js') }}"></script>
    <script src="{{ asset('adminpanel/assets/plugins/chart.js/chart.min.js') }}"></script>
    <script src="{{ asset('adminpanel/assets/pages/dashboard.js') }}"></script><!-- App js -->
    <script src="{{ asset('adminpanel/assets/js/app.js') }}"></script>
